swagger: '2.0'
info:
  version: '1.0.0'
  title: Experimental Monday Feedback API
  description: A REST API that allows people to POST their feedback about experimentation Monday anonymously. Includes a single endpoint. 
  termsOfService: https://apinf.org/terms/
  contact:
    name: APInf Experimentation Monday team
    email: info@apinf.io
    url: http://apinf.io
  license:
    name: EUPL1.1
    url: https://opensource.org/licenses/EUPL-1.1
host: experimentation-mondays-feedback-api.herokuapp.com
basePath: /api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /feedbacks:
    post:
      description: Creates a new feedback for an experimentation monday. 
      operationId: addFeedback
      produces:
        - application/json
      parameters:
        - name: feedback
          in: body
          description: Feedback to add.
          required: true
          schema:
            $ref: '#/definitions/newFeedback'
      responses:
        '200':
          description: feedback response
          schema:
            $ref: '#/definitions/feedback'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  feedback:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
      feeling:
        type: string
      learning:
        type: string
      anticipation:
        type: string
      comment:
        type: string
  newFeedback:
    type: object
    required:
      - feeling
      - learning
      - anticipation
    properties:
      id:
        type: integer
        format: int64
      feeling:
        type: string
      learning:
        type: string
      anticipation:
        type: string
      comment:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
